Repository DenverCoder1/readme-typing-svg, pull requests merged in 2021-04, with the labels that each got.

#1 Updated with heroku url
  README.md
Labels: documentation

#6 Autoload models and views
  composer.json
  composer.lock
  src/index.php
  tests/OptionsTest.php
  tests/RendererTest.php
Labels: refactoring

#8 Escape characters passed to lines to prevent code injection
  src/models/RendererModel.php
  src/templates/main.php
  tests/svg/test_normal.svg
Labels: bug

#13 Add demo site to readme
  README.md
Labels: documentation

#17 Add example to readme
  README.md
Labels: documentation

#15 Replace Demo Screenshot With GIF
  README.md
Labels: documentation

#18 Fix Google Fonts not displaying through image tags
  .gitignore
  README.md
  composer.json
  composer.lock
  src/controllers/RendererController.php
  src/demo/css/loader.css
  src/demo/index.php
  src/demo/js/script.js
  src/index.php
  src/models/DatabaseConnection.php
  src/models/ErrorModel.php
  src/models/GoogleFontConverter.php
  src/models/RendererModel.php
  src/templates/error.php
  src/templates/main.php
  src/views/ErrorView.php
  src/views/RendererView.php
  tests/OptionsTest.php
  tests/RendererTest.php
  tests/svg/test_fonts.svg
  tests/svg/test_missing_lines.svg
  tests/svg/test_normal.svg
Labels: bug

#20 Consistent case and changed PHP version
  README.md
Labels: documentation
