Repository DenverCoder1/readme-typing-svg, pull requests merged in 2022-11, with the labels that each got.

#163 docs(readme): Added CFCIFE to examples
  README.md
Labels: documentation

#165 feature: Added font-weight support
  src/demo/index.php
  src/demo/js/script.js
  src/models/GoogleFontConverter.php
  src/models/RendererModel.php
Labels: enhancement

#167 feat(demo): Added a Reset button
  src/demo/index.php
  src/demo/js/script.js
Labels: enhancement

#170 fix: Consistent use of quotes, simplified tests
  src/templates/main.php
  tests/RendererTest.php
  tests/svg/test_fonts.svg
  tests/svg/test_missing_lines.svg
  tests/svg/test_multiline.svg
  tests/svg/test_normal_vertical_alignment.svg
  tests/svg/test_pause.svg
  tests/svg/test_pause_multiline.svg
Labels: refactoring
